name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > google-credentials.json

      - name: Deploy to your server or run application
        run: |
          # Example: deploy or run your app using the credentials
          # You may want to install dependencies and start your application
          npm install
          npm start
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json